# Generated by Django 3.0.7 on 2020-06-20 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_name', models.CharField(max_length=180, null=True)),
                ('blog_body', models.TextField(null=True)),
                ('status', models.PositiveIntegerField(default=1)),
                ('created_by', models.PositiveIntegerField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
