# Generated by Django 3.0.7 on 2020-06-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='blog_technology',
            field=models.CharField(max_length=180, null=True),
        ),
    ]
